export const NODE_TYPE = {
  CIRCUIT: 'CircuitNode',
  CLOSE_ENDED_QUESTION: 'CloseEndedQuestionNode',
  CONTAINER: 'ContainerNode',
  EMOTION_ATTRIBUTION: 'EmotionAttributionNode',
  EMOTION_ATTRIBUTION_A: 'EmotionAttributionANode',
  EMOTION_ATTRIBUTION_B: 'EmotionAttributionBNode',
  EYES_TASK: 'EyesTaskNode',
  FAUX_PAS: 'FauxPasNode',
  LESSON_TEXT: 'LessonTextNode',
  MULTIPLE_CHOICE_QUESTION: 'MultipleChoiceQuestionNode',
  OPEN_QUESTION: 'OpenQuestionNode',
  EMOTION_RECOGNITION: 'EmotionRecognitionNode',
  SOCIAL_SITUATIONS_EXERCISE_A: 'SocialSituationsExerciseANode',
  SOCIAL_SITUATIONS: 'SocialSituationsNode',
  THEORY_OF_MIND: 'TheoryOfMindNode',
  TRUE_FALSE: 'TrueFalseNode',
  WATCH_VIDEO: 'WatchVideoNode',
} as const;