export const NODE_TYPE = {
  CIRCUIT: 'CircuitNode',
  CLOSE_ENDED_QUESTION: 'closeEndedQuestionNode',
  CONTAINER: 'ContainerNode',
  EMOTION_ATTRIBUTION_A: 'EmotionAttributionANode',
  EMOTION_ATTRIBUTION_B: 'EmotionAttributionBNode',
  EMOTION_ATTRIBUTION_TEST: 'EmotionAttributionTestNode',
  EYES_TASK_TEST: 'EyesTaskTestNode',
  FAUX_PAS: 'FauxPasNode',
  LESSON_TEXT: 'lessonTextNode',
  MULTIPLE_CHOICE_QUESTION: 'multipleChoiceQuestionNode',
  OPEN_QUESTION: 'OpenQuestionNode',
  RICONOSCIMENTO_EMOZIONI: 'RiconoscimentoEmozioniNode',
  SOCIAL_SITUATION_EXERCISE_A: 'SocialSituationExerciseANode',
  SOCIAL_SITUATIONS: 'socialSituationsNode',
  TEORIA_DELLA_MENTE: 'TeoriaDellaMenteNode',
  TRUE_FALSE: 'TrueFalseNode',
  WATCH_VIDEO: 'WatchVideoNode',
} as const;